INFO:__main__:使用 8 个GPU进行训练
WARNING:__main__:未提供backbone路径，请确保设置正确的视觉模型
INFO:__main__:布局模型参数数量: 53,288,966
INFO:__main__:视觉模型参数数量: 393,984
INFO:__main__:总参数数量: 53,682,950
INFO:__main__:train 数据集包含 800 个样本
INFO:__main__:val 数据集包含 200 个样本
INFO:__main__:训练器初始化完成，使用设备: cuda
INFO:__main__:开始训练模式
INFO:__main__:开始训练，共 100 个epoch
Epoch 1/100:   0%|          | 0/25 [00:00<?, ?it/s]Epoch 1/100:   0%|          | 0/25 [00:21<?, ?it/s]
Traceback (most recent call last):
  File "/home/LayoutMaster/train.py", line 1046, in <module>
    main()
  File "/home/LayoutMaster/train.py", line 1001, in main
    trainer.train()
  File "/home/LayoutMaster/train.py", line 740, in train
    loss_dict = self.train_step(batch)
  File "/home/LayoutMaster/train.py", line 484, in train_step
    visual_features = self.visual_extractor(images)  # [B, N, visual_dim]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/parallel_apply.py", line 108, in parallel_apply
    output.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 705, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/parallel_apply.py", line 83, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/LayoutMaster/models.py", line 284, in forward
    raise RuntimeError("Backbone not set. Call set_backbone() first.")
RuntimeError: Backbone not set. Call set_backbone() first.

